AWSTemplateFormatVersion: "2010-09-09"
Description: Generates Secrets Manager entries
Parameters:
  #=======================================================
  #
  #                   CloudFormation Parameters
  #
  #=======================================================
  ManagementApiUsername:
    Type: String
    Description: Management API username
    MinLength: 1
  ManagementApiPassword:
    Type: String
    Description: Management API password
    MinLength: 1
    NoEcho: true
  OpenvpnOnboardingUsername:
    Type: String
    Description: Username for OpenVPN
    MinLength: 1
  OpenvpnOnboardingPassword:
    Type: String
    NoEcho: true
    Description: Password for OpenVPN
    MinLength: 1
  OpenVPNCredentialsSecretName:
    Type: String
    Description: OpenVPN credentials secret name
Resources:
  #=======================================================
  #
  #         Secrets manager parameters resources
  #
  #=======================================================
  ManagementApiCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: open-source-device-onboarding-management-api-credentials
      Description: Management API credentials
      SecretString:
        Fn::Sub: '{"username":"${ManagementApiUsername}", "password": "${ManagementApiPassword}"}'
  OpenvpnOnboardingCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name:
        Ref: OpenVPNCredentialsSecretName
      Description: OpenVPN credentials
      SecretString:
        Fn::Sub: '{"username":"${OpenvpnOnboardingUsername}", "password": "${OpenvpnOnboardingPassword}"}'
Outputs:
  #=======================================================
  #
  #                 CloudFormation Outputs
  #
  #=======================================================
  ManagementApiCredentialsSecretARN:
    Description: Secret ARN of Management API credentials
    Value:
      Ref: ManagementApiCredentialsSecret

  OpenvpnOnboardingCredentialsSecretARN:
    Description: Secret ARN of OpenVpn credentials
    Value:
      Ref: OpenvpnOnboardingCredentialsSecret
