AWSTemplateFormatVersion: "2010-09-09"
Description: "SNS topics for openvpn onboarding notifications"
Resources:
  #=======================================================
  #
  #             SNS resources
  #
  #=======================================================
  SNSFailureTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "onboarding-failure"

  SNSSuccessTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "onboarding-success"

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Sid: "SNS Failure Topic Sid"
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
            Principal:
              AWS: !Sub "${AWS::AccountId}"
            Resource:
              - !Ref SNSFailureTopic
            Condition:
              StringEquals:
                AWS:SourceOwner: !Sub "${AWS::AccountId}"
          - Effect: "Allow"
            Sid: "SNS Success Topic Sid"
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
            Principal:
              AWS: !Sub "${AWS::AccountId}"
            Resource:
              - !Ref SNSSuccessTopic
            Condition:
              StringEquals:
                AWS:SourceOwner: !Sub "${AWS::AccountId}"
      Topics:
        - !Ref SNSFailureTopic
        - !Ref SNSSuccessTopic
Outputs:
  #=======================================================
  #
  #             SNS Outputs
  #
  #=======================================================
  SNSFailureTopicArn:
    Description: Arn for SNS where the onboarding failures will be published
    Value:
      Fn::GetAtt:
        - "SNSFailureTopic"
        - "TopicArn"
  SNSSuccessTopicArn:
    Description: Arn for SNS where the onboarding success events will be published
    Value:
      Fn::GetAtt:
        - "SNSSuccessTopic"
        - "TopicArn"
  SNSFailureTopicName:
    Description: Name for SNS where the onboarding failures will be published
    Value:
      Fn::GetAtt:
        - "SNSFailureTopic"
        - "TopicName"
  SNSSuccessTopicName:
    Description: Name for SNS where the onboarding success events will be published
    Value:
      Fn::GetAtt:
        - "SNSSuccessTopic"
        - "TopicName"
