AWSTemplateFormatVersion: "2010-09-09"
Description: SNS topics for openvpn onboarding notifications
Parameters:
  #=======================================================
  #
  #            CloudFormation Parameters
  #
  #=======================================================
  SNSFailureTopicName:
    Description: Name for SNS where the onboarding failures will be published
    Type: String
  SNSSuccessTopicName:
    Description: Name for SNS where the onboarding success events will be published
    Type: String
  SNSFailureTopicSubscriptionEmail:
    Description: Email for Failure Topic Subscription. Empty string or valid e-mail.
    Type: String
    AllowedPattern: ^$|[^\s@]+@[^\s@]+\.[^\s@]+
  SNSSuccessTopicSubscriptionEmail:
    Description: Email for Success Topic Subscription. Empty string or valid e-mail. Verbose!
    Type: String
    AllowedPattern: ^$|[^\s@]+@[^\s@]+\.[^\s@]+

Conditions:
  #=======================================================
  #
  #            Conditions
  #
  #=======================================================
  SNSFailureTopicSubscriptionEmailExists:
    Fn::Not:
    - Fn::Equals:
        - Ref: SNSFailureTopicSubscriptionEmail
        - ""
  SNSSuccessTopicSubscriptionEmailExists:
    Fn::Not:
      - Fn::Equals:
        - Ref: SNSSuccessTopicSubscriptionEmail
        - ""
Resources:
  #=======================================================
  #
  #             SNS resources
  #
  #=======================================================
  SNSFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Ref: SNSFailureTopicName

  SNSFailureTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Ref: SNSFailureTopicSubscriptionEmail
      Protocol: email
      TopicArn:
        Ref: SNSFailureTopic
    Condition: SNSFailureTopicSubscriptionEmailExists

  SNSSuccessTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Ref: SNSSuccessTopicName

  SNSSuccessTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Ref: SNSSuccessTopicSubscriptionEmail
      Protocol: email
      TopicArn:
        Ref: SNSSuccessTopic
    Condition: SNSSuccessTopicSubscriptionEmailExists

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Sid: SNS Failure Topic Sid
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
            Principal:
              AWS:
                Fn::Sub: ${AWS::AccountId}
            Resource:
              - Ref: SNSFailureTopic
            Condition:
              StringEquals:
                AWS:SourceOwner:
                  Fn::Sub: ${AWS::AccountId}
          - Effect: Allow
            Sid: SNS Success Topic Sid
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
            Principal:
              AWS:
                Fn::Sub: ${AWS::AccountId}
            Resource:
              - Ref: SNSSuccessTopic
            Condition:
              StringEquals:
                AWS:SourceOwner:
                  Fn::Sub: ${AWS::AccountId}
      Topics:
        - Ref: SNSFailureTopic
        - Ref: SNSSuccessTopic
Outputs:
  #=======================================================
  #
  #                 CloudFormation Outputs
  #
  #=======================================================
  SNSFailureTopicArn:
    Description: Arn for SNS where the onboarding failures will be published
    Value:
      Fn::GetAtt:
        - SNSFailureTopic
        - TopicArn
  SNSSuccessTopicArn:
    Description: Arn for SNS where the onboarding success events will be published
    Value:
      Fn::GetAtt:
        - SNSSuccessTopic
        - TopicArn
