AWSTemplateFormatVersion: "2010-09-09"
Description: Generates sim create and disable SQS queues
Resources:
  #=======================================================
  #
  #             SQS Queue resources
  #
  #=======================================================
  SimDisableQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: false
      DelaySeconds: 0
      FifoQueue: true
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30
      QueueName: sims-disable.fifo

  SimCreateQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: false
      DelaySeconds: 0
      FifoQueue: true
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30
      QueueName: sims-create.fifo
Outputs:
  #=======================================================
  #
  #                 CloudFormation Outputs
  #
  #=======================================================
  SimDisableQueueURL:
    Description: URL of Sim Disable SQS Queue
    Value:
      Ref: SimDisableQueue
  SimDisableQueueARN:
    Description: ARN of Sim Disable Queue
    Value:
      Fn::GetAtt:
        - SimDisableQueue
        - Arn
  SimDisableQueueName:
    Description: Name of Sim Disable Queue
    Value:
      Fn::GetAtt:
        - SimDisableQueue
        - QueueName
  SimCreateQueueURL:
    Description: URL of Sim Create SQS Queue
    Value:
      Ref: SimCreateQueue
  SimCreateQueueARN:
    Description: ARN of Sim Create Queue
    Value:
      Fn::GetAtt:
        - SimCreateQueue
        - Arn
  SimCreateQueueName:
    Description: Name of Sim Create Queue
    Value:
      Fn::GetAtt:
        - SimCreateQueue
        - QueueName
