name: Device-Onboarding-checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
     image: node:14

    steps:
    - name: Checkout code
      uses: actions/checkout@v2            
    
    - name: Navigate to applications folder
      run: cd applications

    - name: Install node dependencies
      run: npm ci

    - name: Run Unit tests
      run: npm run test -- --ci --coverage --reporters=default --reporters=jest-junit

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: applications/junit.xml
        reporter: java-junit
        fail-on-error: true
    
