name: Device-Onboarding-checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x 

    - name: Run Unit tests
      run: |
        cd applications
        npm ci
        npm run test -- --ci --coverage --reporters=default --reporters=jest-junit

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Jest Tests
        path: applications/junit.xml
        reporter: jest-junit
        fail-on-error: true
